name: app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.4.0
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  http: ^0.13.4
  dartz: ^0.10.1
  flutter_modular: ^5.0.3
  equatable: ^2.0.3
  firebase_core: ^1.19.0

dev_dependencies:
  test: ^1.21.4
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
