name: app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.0
  bloc: ^8.0.3
  dartz: ^0.10.1
  flutter_modular: ^5.0.3
  equatable: ^2.0.3
  firebase_core: ^1.19.2
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_storage: ^10.0.6
  google_sign_in: ^5.4.0
  flutter_bloc: ^8.0.1
  mask_text_input_formatter: ^2.3.0
  flutter_svg: ^1.1.1+1
  flutter_google_places: ^0.3.0
  encrypt: ^5.0.1
  url_launcher: ^6.1.5
  flutter_config: ^2.0.0
  image_picker: ^0.8.5+3
  perfect_volume_control: ^1.0.5
  flutter_linkify: ^5.0.2

dev_dependencies:
  # flutter_launcher_icons: "^0.9.2"
  mocktail: ^0.3.0

# flutter_icons:
#   ios: true
#   android: true
#   image_path_ios: "assets/images/icon.png"
#   image_path_android: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/svg/
   - assets/audios/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic

